// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BackgroundGalaxy: typeof import('./components/BackgroundGalaxy.vue')['default']
    'Carbon:cloudServices': typeof import('~icons/carbon/cloud-services')['default']
    'Carbon:directLink': typeof import('~icons/carbon/direct-link')['default']
    'Carbon:home': typeof import('~icons/carbon/home')['default']
    'Carbon:logoGithub': typeof import('~icons/carbon/logo-github')['default']
    'Carbon:microscope': typeof import('~icons/carbon/microscope')['default']
    'Carbon:notebook': typeof import('~icons/carbon/notebook')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSearch: typeof import('~icons/carbon/search')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Post: typeof import('./components/Post.vue')['default']
    SearchFilter: typeof import('./components/search/SearchFilter.vue')['default']
    SearchInput: typeof import('./components/search/SearchInput.vue')['default']
    'Teenyicons:typescriptOutline': typeof import('~icons/teenyicons/typescript-outline')['default']
    TodayList: typeof import('./components/TodayList.vue')['default']
    TopControl: typeof import('./components/TopControl.vue')['default']
  }
}

export { }
