// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BackgroundGalaxy: typeof import('./components/BackgroundGalaxy.vue')['default']
    'Carbon:navaidVortac': typeof import('~icons/carbon/navaid-vortac')['default']
    CarbonBook: typeof import('~icons/carbon/book')['default']
    CarbonHome: typeof import('~icons/carbon/home')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Post: typeof import('./components/Post.vue')['default']
    SearchFilter: typeof import('./components/search/SearchFilter.vue')['default']
    SearchInput: typeof import('./components/search/SearchInput.vue')['default']
    TodayList: typeof import('./components/TodayList.vue')['default']
    TopControl: typeof import('./components/TopControl.vue')['default']
    WasmHandlePicture: typeof import('./components/demo/wasm-handle-picture.vue')['default']
  }
}

export { }
